### ISSUE TITLE
Allow users to patch files that aren't rom files.

### ISSUE THREAD

**Issue by Twig6943** [em-s-h/xdelta_lui#2]
title

**Comment by Twig6943** [comment]
I've made a fork of the project which will be removed if you decide to add the said feature. https://github.com/Twig6943/xdelta_lui-/tree/main

**Comment by em-s-h** [comment]
Wow that's a lot of changes! I am about to add this feature right now.

**Comment by Twig6943** [comment]
ye literally changed 2 files

**Comment by Twig6943** [comment]
could u also package the app as appimage? I've failed to do so

**Comment by em-s-h** [comment]
> could u also package the app as appimage? I've failed to do so

I'll see what I can do.
