### ISSUE TITLE
Could you do the same fix for V1.0.1

### ISSUE THREAD

**Issue by Twig6943** [em-s-h/xdelta_lui#3]
This version does open up on my machine (https://github.com/em-s-h/xdelta_lui/releases/tag/v1.0.1) but it doesn't have this fix https://github.com/em-s-h/xdelta_lui/issues/2

**Comment by Twig6943** [comment]
Also is the appimage cancelled cuz u marked the issue as closed?

**Comment by em-s-h** [comment]
> Also is the appimage cancelled cuz u marked the issue as closed?

Oh no, I closed the issue since the title is "Allow users to patch files that aren't rom files." which was fixed, I'm still going to try making the appimage.

**Comment by em-s-h** [comment]
> This version does open up on my machine (https://github.com/em-s-h/xdelta_lui/releases/tag/v1.0.1) but it doesn't have this fix #2

Yeah, I'm not going to maintain 2 different versions of the app (before and after gtk 4.10), so you'll either have to patch the fix in that version or wait for a possible appimage.

**Comment by Twig6943** [comment]
Could u just upload this to the releases tab https://github.com/Twig6943/xdelta_lui-/releases/download/1.0/xdelta_lui so I can remove my fork. (This is version 1.0.1 with the fix.)

**Comment by em-s-h** [comment]
Ok, added!
